# -*- coding: utf-8 -*-
"""Copy of DL-Sheet03-CIFAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJmIxeV-FyMpFWdJTkh1HiDdd1_nJ0r9

# Deep Learning - Winter Term 2025/2026

<hr style="border:2px solid gray">

### Exercise Sheet 03

<br>

## 4.2 Train a CNN on CIFAR10

Finally we deal with a more challenging task -- CIFAR10. It is a dataset consisting of RGB pictures of objects. Thankfully, CIFAR is also a popular dataset and can be donwloaded using Torchvision just like MNIST.

__General remark:__ We suggest you to go through the code and understand what this exercise is about before coding. You might find some tasks that come later easier than the previous tasks and solving them could give you better understanding.

__Note:__ CIFAR10 is a large dataset and training needs much computation power. Therefore it is recommended to use [Google Colab](https://colab.research.google.com).

Without further ado, let's get to it!
"""

# We start with importing some necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import time

# A lot of PyTorch stuff
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
import torchvision
from torchvision.utils import make_grid
from torchvision import datasets
from torchvision.transforms import v2

# TODO: Implement the __init__ and forward method of the CNN class.
# Here are some hints you should take into account
#     - As you learned in the lecture, typically fully-connected layers
#       follow the convolution blocks. So do not forget to flatten the appropriate dimension
#       A linear layer expects input size (B, H), where B is batch size and H is feature size.
#       Check the PyTorch documentation for details.
#     - Our aim is to learn different regularization strategies. You can try any methodlogy
#       that seems reasonable to you *but* Dropout is highly recommended in this setting.
#     - We will use the negative log-likelihood as the loss function, keep it in mind
#       when choosing the output function.
#     - Which activation function you choose can be decisive here.


class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        # First Convolution Block
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=5, padding=2)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        # Second Convolution Block
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=5, padding=2)
        self.fc1 = nn.Linear(32 * 8 * 8, 256) # Fully Connected layer
        self.dropout = nn.Dropout(p=0.5) # Dropout layer

        # Output layer
        self.fc2 = nn.Linear(256, 10)


    def forward(self, x):

        # For first block
        x = self.conv1(x)
        x = F.relu(x) # ReLU Activation Function is used
        x = self.pool(x)

        # For second block
        x = self.conv2(x)
        x = F.relu(x)
        x = self.pool(x)

        x = x.view(-1, 32 * 8 * 8) # Here we flattening tensor as told in hints.

        # For Fully Connected layers
        x = self.fc1(x)
        x = F.relu(x)
        x = self.dropout(x) # Also added dropout layer as told in hints.
        x = self.fc2(x)
        return x

# We can test if the forward pass runs smoothly
# Following chunk should print torch.Size([1, 10])
t = torch.randn(1,3,32,32)
model = CNN()
model(t).shape

"""### Data preprocessing
In the following, we will download and preprocess the dataset. This process **do not** have to be done after implementing the model architecture. It solely depends on your thought flow.
"""

# In the first step, we find the mean and standard deviation of the training data.
# We would like to normalize these stats to ensure a nice network flow.

# Download the training dataset
ds_train = datasets.CIFAR10('./data', train=True, download=True)
# Take only the images
ims_train = torch.tensor(ds_train.data)
ims_train = ims_train.float() / 255.

# Let's look at the data. It is always a good idea to know what is in the dataset.
labels = {0:"airplane",1:"automobile",2:"bird",3:"cat",4:"deer",5:"dog",6:"frog",7:"horse",8:"ship",9:"truck"}
fig, ax = plt.subplots(4,4,figsize=(3,3))
for i, c_ax in enumerate(ax.flatten()):
    im, lab = ds_train[i]
    c_ax.imshow(im)
    c_ax.set_title(labels[lab],fontsize=6, y=0.88)
    c_ax.axis('off')

# TODO: compute the mean and std
# Hint: we need the stats of each channel.So, it should be three dimensional.

# mean calculation in dimension order of the batch, height, and width.
mu = torch.mean(ims_train, dim=(0, 1, 2))

# similalry std calculation
std = torch.std(ims_train, dim=(0, 1, 2))

print("Mean (mu):", mu)
print("Std (std):", std)

"""We are approaching to finalize the preprocessing. Following is an important step to make our model more generalizable. We will manipulate the data in order to create more '''diversity''' in the data. Especially, we want to make use of data augmentation. Torchvision has many different pre-implemented augmentation methodologies. Here is a nice starter in the documentation:

[Getting started with Transforms v2](https://pytorch.org/vision/stable/auto_examples/transforms/plot_transforms_getting_started.html#sphx-glr-auto-examples-transforms-plot-transforms-getting-started-py)
"""

# TODO: Apply data augmentation using transforms v2.
#
# Training data:
#   - Apply a random crop with size 32 on a padded version of the image with p=4
#   - Flip each image 40% horizontally
#   - Transform to a Image
#   - Normalize with the constants calculated above
# Test data:
#   - Transform to a Tensor
#   - Normalize with the constants calculated above
#
# Please also add "v2.ToDtype(torch.float32, scale=True)"
# as it is shown in the starter text. It is needed.
#
# Finally build train and test dataloaders with batch size 128 and 2 workers
# We shuffle the traning set to exploit the stochasticity


# Training data
v2_train = v2.Compose([
    v2.RandomHorizontalFlip(p=0.5),
    v2.RandomCrop(32, padding=4),
    v2.ToTensor(),
    v2.Normalize(mean=mu, std=std)
])

# Test Data
v2_test = v2.Compose([
    v2.ToTensor(),
    v2.Normalize(mean=mu, std=std)
])

ds_train = datasets.CIFAR10('./data', train=True, download=True, transform=v2_train)
ds_test = datasets.CIFAR10('./data', train=False, download=True, transform=v2_test)

print(f'Train data -> {ds_train.data.shape}')
print(f'Test data -> {ds_test.data.shape}')

dl_train = DataLoader(ds_train, batch_size=128, shuffle=True, num_workers=2)
dl_test = DataLoader(ds_test, batch_size=128, shuffle=False, num_workers=2)
print("\nTrain DataLoader and Test DataLoader created successfully.")

# Here in Augmantation, I have added random horizontal flip around 50% and random crop with padding 4. Now as you requested add "v2.ToDtype(torch.float32, scale=True)"
# so for that we have used v2.ToTensor() which is standard way which follows both instruction("Transform to a Tensor" and "ToDtype/scale") in one line.
# And than we used normalize function to normalize both mean and std.

# We can now look into the augmented data.
for images, labels in ds_train:
        fig, ax = plt.subplots(figsize=(12, 6))
        ax.set_xticks([]); ax.set_yticks([])
        ax.imshow(make_grid(images, nrow=12).permute(1, 2, 0))
        break

"""Almost there! We only need to code the training and test loops. Note that this implementation is slightly different than the previous exercise. This time we will wrap the training and testing process in a method and call the methods for each epoch. We provide you ```test``` but you need to complete the ```train```method."""

def test(model, dl_test, criterion, device='cpu'):
    """
    model: model to test
    dl_test: test data
    criterion: loss function
    device: device to test on
    """
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad(): # no need to track gradients. Saves memory.
        for images, labels in dl_test:
            images, labels = images.to(device), labels.to(device)
            output = model(images) # Forward pass
            test_loss += criterion(output, labels).item()  # sum up batch loss
            pred = output.data.max(1, keepdim=True)[1]
            correct += pred.eq(labels.data.view_as(pred)).sum() # get the correct predictions

    test_loss /= len(dl_test.dataset)
    accuracy = 100. * correct / len(dl_test.dataset)

    print('\nTest set - Average loss: {:.4f}, Accuracy: {}/{} ({:.3f}%)\n'.format(
        test_loss, correct, len(dl_test.dataset),
        accuracy.item()))

# TODO: Implement the train method
# You basically need to implement the common training block

def train(model, dl_train, optimizer, epoch, criterion, log_interval=100, device='cpu'):
    """
    model: model to train
    dl_test: train data
    optimizer: optimization algorithm
    epoch: current epoch
    criterion: loss function
    log_interval: printing interval
    device: device to train on
    """
    model.train()
    correct = 0
    total = 0
    train_loss = 0.
    for batch_idx, (images, labels) in enumerate(dl_train):
        images, labels = images.to(device), labels.to(device)

        # Implementation of training method
        optimizer.zero_grad()
        output = model(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()

       # Get some statistics
        train_loss += loss.detach().item()
        pred = output.data.max(1, keepdim=True)[1]
        correct += pred.eq(labels.data.view_as(pred)).sum()
        total += args.batch
        train_acc = 100 * correct / total

        if batch_idx % log_interval == 0:
            print(f"Epoch {epoch + 1}/{batch_idx + 1} -> {train_loss / (batch_idx + 1)} --- acc -> {train_acc}%")

# In training method we have used zero_grad() to avoid gpu load and memory error. Then output of the model and loss calculation of outputs and true labels,
# and then we have used loss calculation of backward to calculate gradients of the loss and finally update the model parmeters using computed gradients.

"""Yee-haw! Finally we can train our model!"""

# Seed for reproducibility
torch.manual_seed(4321)

# Initialize the model
model = CNN()

# TODO: initialize the optimizer.
#   - Use SGD with momentum
#   - Apply L2 penalty (weight_decay)
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9, weight_decay=5e-4)

# TODO: set criterion
criterion = nn.CrossEntropyLoss()

# Following code applies a learning rate schedule such that it changes after each epoch.
# It is pre-implemented in torch.optim. Pretty neat, huh?
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=200)

# Here we write down the optimizer and criterion and in the criterion we are using Cross-entropy loss because it combines softmax operation with negative log-likelihood.
# And also use in multiclass classification problem.

# run()
a = time.time()

epochs = 5
for epoch in range(epochs):
    train(model, dl_train, optimizer, epoch, criterion, log_interval=10)
    test(model, dl_test, criterion)
    scheduler.step()

b = time.time()
print('\nTraining took ' + str(np.round(b - a, 2)) + ' seconds.\n\n')

"""This should give us around $35-40\%$ accuracy. The performance is a lot better than random, but we can definitely increase it. Before doing that, if you are not already on Google Colab, you probably realize that your machine is stressed out and the training took much time. Let us now use a GPU and see how much difference it makes. If available, you can use the one in your computer. If not, you can just move to Colab.

On Colab, to use a GPU, follow on the collaboratory menu tabs, "Runtime" -> "Change runtime type" and set it to GPU. Then run the same training loop but now on GPU.

**Note:** There are no TODOs in this part. It is just about the speed.
"""

# Let's speed up!
device = 'cuda'
if device == 'cuda': torch.backends.cudnn.benchmark = True # additional speed up

model = CNN()
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9, weight_decay=5e-4)
criterion = nn.CrossEntropyLoss()

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=200)
model = model.to(device)

# The notebook should have defined 'device' in the previous cell like this:
# device = 'cuda'

# run()
a = time.time()

epochs = 5
for epoch in range(epochs):
    train(model, dl_train, optimizer, epoch, criterion, log_interval=10, device=device)
    test(model, dl_test, criterion, device=device)
    scheduler.step()

b = time.time()
print('\nTraining took ' + str(np.round(b - a, 2)) + ' seconds.\n\n')

"""This should be way faster now. The fact that we can train the model faster does not only save us time. More importantly, it allows us to scale up the models and still train them in a reasonable amount of time. Now it is time to increase the performence as well.

Again, PyTorch is very helpful. We can just initialize a state-of-the-art model and train it. You will learn this model in the lecture.
"""

from torchvision.models import resnet18

model = resnet18()
model

"""Looks massive but it is a highly efficient model that implements a very simple idea, i.e. **the residual block**. However, these models are developed for Imagenet dataset, which has $1000$ classes. So we need to adapt the output layer of the model.

Currently the last layer is:
```
  (fc): Linear(in_features=512, out_features=1000, bias=True)
```
"""

# TODO: Adapt ResNet to train on CIFAR10

model = resnet18()

num_ftrs = model.fc.in_features # Get the number of input features for the final layer
model.fc = nn.Linear(num_ftrs, 10) # This final layer will produce 10 outputs for 10 diffrent classes
print(model.fc)

# Let's speed up!
device = 'cuda'
if device == 'cuda': torch.backends.cudnn.benchmark = True

model = CNN()
optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9, weight_decay=5e-4)
criterion = nn.CrossEntropyLoss()

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=200)
model = model.to(device)

import time

# run()
a = time.time()

epochs = 20
for epoch in range(epochs):
    train(model, dl_train, optimizer, epoch, criterion, log_interval=50, device=device)
    test(model, dl_test, criterion, device=device)
    scheduler.step()

b = time.time()
print('\nTraining took ' + str(np.round(b - a, 2)) + ' seconds.\n\n')

"""Now, we should reach over $50\%$. Is it good? Actually, we can do it even better!

***Bonus exercise:*** Achieve test accuracy $>90$. You can change many things to reach this performence (e.g. architecture, optimizer, regularization methods, different hyperparameters).
"""

# To achive more than 90% accuracy we are going to use new deep CNN model with BatchNormlization. In the new CNN model we add deeper blocks to extract
# Deeper features.

class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        # Input Block
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=64, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(64) # Batch Normalization is key for deeper models

        # Block 2
        self.conv2 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(128)
        self.pool1 = nn.MaxPool2d(2, 2) # 32x32 -> 16x16

        # Block 3
        self.conv3 = nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(256)

        # Block 4
        self.conv4 = nn.Conv2d(in_channels=256, out_channels=256, kernel_size=3, padding=1)
        self.bn4 = nn.BatchNorm2d(256)
        self.pool2 = nn.MaxPool2d(2, 2) # 16x16 -> 8x8

        # Fully Connected Classifier
        self.fc1 = nn.Linear(256 * 8 * 8, 1024) # Flattened size is 256 channels * 8 height * 8 width = 16384
        self.fc2 = nn.Linear(1024, 512)
        self.fc3 = nn.Linear(512, 10)
        self.dropout = nn.Dropout(0.5) # Dropout layer to tackle overfitting problem

    def forward(self, x):
        # For Input Block
        x = F.relu(self.bn1(self.conv1(x)))

        # For Block 2
        x = F.relu(self.bn2(self.conv2(x)))
        x = self.pool1(x)

        # For Block 3
        x = F.relu(self.bn3(self.conv3(x)))

        # For block 4
        x = F.relu(self.bn4(self.conv4(x)))
        x = self.pool2(x)

        # For classifier
        x = x.view(-1, 256 * 8 * 8) # Flatten layer
        x = self.dropout(F.relu(self.fc1(x)))
        x = self.dropout(F.relu(self.fc2(x)))
        x = self.fc3(x)

        return x

# Improved CNN architecture explanation:

# 1) First Convolution block: in This block it tackes the RGB image as input and converts it into 64 feature maps using a 3×3 convolution kernel.
#    Batch Normalization is applied to stabilize training and ReLU is used as the activation function.

# 2) Second Convolution block: The output from the first block is passed to this block, where the number of feature maps is increased
#    from 64 to 128. Batch Normalization and ReLU are again applied. A max-pooling layer is used to reduce the spatial dimension

# 3) Third Convolution block: This block further increases the depth of the network by expanding the feature maps from 128 to 256.
#    Batch Normalization and ReLU help in learning deeper representations while maintaining stable gradients.

# 4) Fourth Convolution block: This block keeps the number of feature maps at 256 and applies another convolution operation.
#    Batch Normalization and ReLU are used again, followed by max-pooling which reduces the spatial size from 16×16 to 8×8.
#    This block helps the model learn high-level and abstract features.

# 5) Fully Connected layers: The final feature maps are flattened into a 1D vector of size 256 × 8 × 8 = 16384.
#    This vector is passed through two fully connected layers with 1024 and 512 neurons respectively.
#    Dropout is applied to reduce overfitting. The final fully connected layer outputs 10 values.

import torch.optim as optim

# Set up the device
device = 'cuda'

# --- Initialize the New Model ---
bonus_model = CNN().to(device)

# --- Hyperparameters ---
EPOCHS_BONUS = 50  # We need more epochs for a deeper model
LEARNING_RATE = 0.1 # Start with a higher learning rate
MOMENTUM = 0.9
WEIGHT_DECAY = 5e-4

# --- Optimizer and Loss ---
optimizer_bonus = optim.SGD(bonus_model.parameters(), lr=LEARNING_RATE, momentum=MOMENTUM, weight_decay=WEIGHT_DECAY)
criterion = nn.CrossEntropyLoss()

# --- Scheduler ---
# Let the scheduler know the total number of epochs it will run for
scheduler_bonus = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer_bonus, T_max=EPOCHS_BONUS)

import time
import numpy as np

# Use your original 'dl_train' and 'dl_test' dataloaders
# Ensure your 'train' and 'test' functions are defined from before

a = time.time()

for epoch in range(EPOCHS_BONUS):
    # Use the new model, optimizer, and scheduler
    train(bonus_model, dl_train, optimizer_bonus, epoch, criterion, log_interval=50, device=device)
    test(bonus_model, dl_test, criterion, device=device)

    # The scheduler takes a step after each epoch
    scheduler_bonus.step()

b = time.time()
print(f'\nBONUS Training took {np.round(b - a, 2)} seconds.\n')

# And in the result we can say that it achives 91.520% which is more then 90% testing accuracy, so we can conclude that if we use deeper CNN architecture
# with deeper Convolution block and with Correct normalization method we can get the higher accuracy. and also in this assignment we have used more deeper
# CNN architecture with batch normalization and with custom hyperparameter gives more than 90% accuracy.